kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

trigger:
  branch:
  - master
  event:
  - push

clone:
  depth: 1

steps:
- name: build
  commands:
  - gradle build
  - docker build -t aulang/oauth .

- name: stop
  commands:
  - docker stop oauth
  - docker rm oauth

- name: deploy
  commands:
  - rm -rf /var/log/oauth/*
  - docker run -d -v /var/log/oauth:/var/log/oauth --name=oauth --net=host --restart=always aulang/oauth
