stages:
  - build
  - stop
  - deploy

build_image:
  stage: build
  only:
    - master
  script:
    - gradle build
    - docker build -t aulang/oauth .

stop_service:
  stage: stop
  only:
    - master
  script:
    - docker stop oauth
    - docker rm oauth
    - docker rmi $(docker images | grep "none" | awk '{print $3}')

deploy_service:
  stage: stop
  only:
    - master
  script:
    - rm -rf /var/log/oauth/*
    - docker run -d -v /var/log/oauth:/var/log/oauth --name=oauth --net=host --restart=always aulang/oauth
