server:
  port: 8080
  servlet:
    context-path: /oauth
    session:
      cookie:
        http-only: true

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/oauth

captcha:
  len: 2
  width: 100
  height: 42
  style: Math
