server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /oauth
    session:
      cookie:
        http-only: true

spring:
  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: oauth
      username: adminx
      password: unicloud
      authentication-database: admin

captcha:
  len: 2
  width: 100
  height: 42
  style: Math
