server:
  port: 8080
  servlet:
    context-path: /oauth
    session:
      cookie:
        http-only: true
  tomcat:
    remote-ip-header: X-Real-IP
    protocol-header: X-Forwarded-Proto

spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/oauth

captcha:
  count: 4
  width: 200
  height: 80
  style: shear

email:
  host: smtp.aliyun.com
  port: 465
  ssl-enable: true
  auth: true
  user: aulang@aliyun.com
  pass: xxxxxxxxxxxxxxxxx
  from: aulang@aliyun.com